
services:
  steamcmd:
    image: pickonefish/steamcmd-dst:rocky-8
    container_name: dst_server
    #stdin_open: true
    #tty: true
    #entrypoint: /bin/sh
    entrypoint: /root/steamapps/DST/run_dedicated_server.sh
    volumes:
      - ./.klei:/root/.klei
      - ./DST:/root/steamapps/DST
