
services:
  steamcmd:
    image: steamcmd/steamcmd:rocky-8
    container_name: dst_server
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    #entrypoint: ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4 & /root/steamapps/DST/run_dedicated_server.sh
    volumes:
      - ./.klei:/root/.klei
      - ./DST:/root/steamapps/DST
